### ISSUE TITLE
Large runs failing due to producing cmds which exceed powershell's max command length of 8191 characters

### ISSUE THREAD

**Issue by Graeme-Smith** [moka-guys/process_duty_csv#8]
When running NGS523 through process_duty_email.py the script failed as the command produced & streamed to the powershell terminal was too long and exceeded the maximum length of a command  (8191 characters).  Long commands will need batching and streaming to powershell in smaller chunks.

**Comment by RachelDuffin** [comment]
Suggestion to run a winget command per file as opposed to batching as this should require a simple for loop. Should be more straightforward than calculating the length of the command and adding additional URLs / re counting until the max command length is reached

**Comment by RachelDuffin** [comment]
This is now solved by download per file
